# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted  # Running on a self-hosted runner

    strategy:
      matrix:
        node-version: [18.x]  # Node.js version matrix

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4  # Setup Node.js with caching for Yarn
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install  # Install the project dependencies

    - name: Build the project
      run: yarn build --if-present  # Build the project if applicable

    - name: Setup .env file with PROD_ENV_FILE secret
      run: |
        if [ -z "${{ secrets.PROD_ENV_FILE }}" ]; then
          echo "Error: PROD_ENV_FILE secret is not set" >&2
          exit 1
        fi
        echo "${{ secrets.PROD_ENV_FILE }}" > .env  # Create .env file with PROD_ENV_FILE secret

    - name: Run tests
      run: yarn test  # Optional: Run tests if you have test scripts configured




