# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --frozen-lockfile    
    - name: Setup Environment
      run: |
        if [ -z "${{secrets.PROD_ENV_FILE}}" ]; then
          echo "Error: PROD_ENV_FILE secret is not set" >&2
          exit 1
        fi
        touch .env
        echo "${{secrets.PROD_ENV_FILE}}" > .env
    - name: Restart Application with PM2
      run: pm2 restart BackendAPI